# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Never
email: me@never.tw
description: > # this means to ignore newlines until "baseurl:"
  技男爱技术
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.never.tw" # the base hostname & protocol for your site
twitter_username: Never_Min
github_username:  nevermin

# Build settings
markdown: kramdown
drafts: --drafts
